const customLang = {
  en: {
    title: "Periodic table of Elements",
    legend: "Legend",
    search: "Enter the name of the element or the symbol",
    elements: "Lanthanides",
    paragraph: "Actinides",
    alcal: "Alcali metals",
    alcalEarth: "Alcali Earth Metals",
    transitions: "Transition Metals",
    other: "Other Metals",
    metal: "Metalloids",
    nonMetal: "Non-Metals",
    halogens: "Halogens",
    nobleGas: "Noble Gases",
    about: "Developed by the students of the academy",
    mail: "E-mail:",
    atomicMass: "Atomic weight",
    density: "Density",
    meltingPoint: "Melting Point",
    boiling: "Boiling Point",
    unknown: "unknown",
    details: "Element detail-PDF",
    symbols: "Symbol",
    atomicNum: "Atomic number",
    phase: "Phase",
    absMeltPoint: "Absolute melting point",
    absBoilPoint: "Absolute boiling point",
    preasure: "Critical preasure",
    temperature: "Critical temperature",
    heatFusion: "Heat of fusion",
    heatVaporization: "Heat of vaporization",
    heatCombustion: "Heat of combustion",
    heat: "Specific heat",
    index: "Adiabatic index",
    neel: "Neel point",
    thermal: "Thermal conductivity",
    expansion: "Thermal expansion",
    liquid: "Density(liquid)",
    molarV: "Molar volume",
    brinelHardness: "Brinell hardness",
    mohs: "Mohs hardness",
    vickers: "Vickers hardness",
    shear: "Shear modules",
    bulk: "Bulk modules",
    molarHeat: "Molar heat",
    thermalExp: "Thermal expansion",
    valence: "Valence",
    electronegativity: "Electronegativity",
    afinity: "Electron afinity",
    ionization: "Ionization energy",
    autoigniton: "Autoignition point",
    flashpoint: "Flashpoint",
    alternateName: "Alternate names",
    namesOfAlotropes: "Names of allotropes",
    block: "Block",
    group: "Group",
    period: "Period",
    color: "Color",
    discovery: "Discovery",
    gasPhase: "Gas phase",
    elType: "Electrical type",
    conductivity: "Electrical conductivity",
    resistvity: "Resistivity",
    superconductic: "Superconducting point",
    magneticType: "Magnetic type",
    curePoint: "Cure point",
    massMagnetic: "Mass magnetic susceptibility",
    molarMagnetic: "Molar magnetic susceptibility",
    volumeMagnetic: "Volume magnetic susceptibility",
    inUniverse: "In universe",
    sun: "In sun",
    meteoritis: "In meteoritis",
    earths: "In earth's crust",
    oceans: "In oceans",
    humans: "In humans",
    atomicRadius: "Atomic radius",
    covalent: "Covalent radius",
    vanDerWalls: "Van der Walls radius",
    crystal: "Crystal structure",
    laticeAngles: "Latice angles",
    laticeConstants: "Latice constants",
    spaceGr: "Space group name",
    spaceNum: "Space group number",
    half: "Half life",
    lifetime: "Lifetime",
    decay: "Decay mode",
    quantum: "Quantum numbers",
    neutron: "Neutron cross section",
    neutronMass: "Neutron mass absorption",
    isotopes: "Known isotopes",
    stable: "Stable isotopes",
    isotopic: "Isotopic abundances",
    overview: "Overview",
    thermalProp: "Thermal Properties",
    physicalProp: "Physical Properties",
    reactivity: "Reactivity",
    safety: "Safety",
    classification: "Classifications",
    electrical: "Electrical Properties",
    magnetic: "Magnetic Properties",
    abundances: "Abundances",
    atomicDimensions: "Atomic dimensions and structures",
    nuclear: "Nuclear Properties",
    detailsSearch: "Search",
  },
  mk: {
    title: "Периодна табела на елементи",
    legend: "Легенда",
    search: "Внесете го името на елементот или симболот",
    elements: "Лантаниди",
    paragraph: "Актиниди",
    alcal: "Алкални метали",
    alcalEarth: "Алкали Земја метали",
    transitions: "Транзициони метали",
    other: "Други метали",
    metal: "Металоиди",
    nonMetal: "Неметали",
    halogens: "Халогени",
    nobleGas: "Благородни гасови",
    about: "Изработено од студентите на академијата",
    mail: "Е-маил:",
    atomicMass: "Атомска тежина",
    density: "Густина",
    meltingPoint: "Точка на топење",
    boiling: "Точка на вриење",
    unknown: "непознато",
    details: "Детали за елементот-PDF",
    symbols: "Симбол",
    atomicNum: "Атомски број",
    phase: "Фаза",
    absMeltPoint: "Абсолутн точка на топење",
    absBoilPoint: "Апсолутна точка на вриење",
    preasure: "Критички притисок",
    temperature: "Критична температура",
    heatFusion: "Топлина на фузија",
    heatVaporization: "Топлина на испарување",
    heatCombustion: "Топлина на согорување",
    heat: "Специфична топлина",
    index: "Адиабатски индекс",
    neel: "Нил точка",
    thermal: "Термичка спроводливост",
    expansion: "Термичка експанзија",
    liquid: "Густина (течност)",
    molarV: "Моларен волумен",
    brinelHardness: "Тврдост на Бринел",
    mohs: "Мохсова цврстина",
    vickers: "Масовно модул",
    shear: "Модул на смолкнување",
    bulk: "Масовно модул",
    molarHeat: "Моларната топлина",
    thermalExp: "Термички измазнување",
    valence: "Валентност",
    electronegativity: "Електронегативност",
    afinity: "Електронска афинитет",
    ionization: "Jонска енергија",
    autoigniton: "Точка на автониг",
    flashpoint: "Флеш точка",
    alternateName: "Алтернативни имиња",
    namesOfAlotropes: "Имиња на алотропи",
    block: "Блокирај",
    group: "Група",
    period: "Период",
    color: "Боја",
    discovery: "Откриено",
    gasPhase: "Гасна фаза",
    elType: "Електричен тип",
    conductivity: "Електрична спроводливост",
    resistvity: "Отпорност",
    superconductic: "Суперспроводлива точка",
    magneticType: "Магнетен тип",
    curePoint: "Точка на лекување",
    massMagnetic: "Масовна магнетна осетливост",
    molarMagnetic: "Моларна магнетна осетливост",
    volumeMagnetic: "Волуменска магнетна осетливост",
    inUniverse: "Во универзум",
    sun: "Во сонце",
    meteoritis: "Во метеоритис",
    earths: "Во земјата кора",
    oceans: "Во океаните",
    humans: "Во луѓето",
    atomicRadius: "Атомски радиус",
    covalent: "Ковалентен радиус",
    vanDerWalls: "Ван дер Валс радиус",
    crystal: "Кристална структура",
    laticeAngles: "Лакови агли",
    laticeConstants: "Константи на латекс",
    spaceGr: "Име на просторната група",
    spaceNum: "Број на просторна група",
    half: "Пола живот",
    lifetime: "Доживотна",
    decay: "Режим на распаѓање",
    quantum: "Квантитативен број",
    neutron: "Неутронски пресек",
    neutronMass: "Апсорпција на неутронска маса",
    isotopes: "Познати изотопи",
    stable: "Стабилни изотопи",
    isotopic: "Изотопски изобили",
    overview: "Преглед",
    thermalProp: "Топлински својства",
    physicalProp: "Физички својства",
    reactivity: "Реактивност",
    safety: "Сигурност",
    classification: "Класификации",
    electrical: "Електрични својства",
    magnetic: "Магнетни својства",
    abundances: "Богатства",
    atomicDimensions: "Атомски димензии и структури",
    nuclear: "Нуклеарни својства",
    detailsSearch: "Пребарај",
  },
};
